### ISSUE TITLE
Not available in modules and will not work trying to import from github.

### ISSUE THREAD

**Issue by MatterL** [Nargath/fvtt-crit-hits-and-fumbles-pf1#1]
The module is not available in the Foundry VTT module installer, and taking the direct link to the json gives the error " ... does not provide a download URL that can be installed."

**Comment by Nargath** [comment]
Unfortunately I’ve been denied to have this listed with the other modules, as it contains material that is not under the OGL licence.

To install it, try using the raw link the module.json file.

https://raw.githubusercontent.com/Nargath/fvtt-crit-hits-and-fumbles-pf1/main/module.json

Let me know if that still doesn’t work.

**Comment by MatterL** [comment]
Well I'd tried that one previously and got the same issue, BUT

Now it suddenly works of course. Thank you for the swift response, sorry this awesome tool can't be more official!
